# Generated by Django 3.2.8 on 2021-11-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observe',
            name='receive_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
