# Generated by Django 3.2.3 on 2021-11-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_observe_receive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='real_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
