# Generated by Django 3.2.3 on 2021-11-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_item_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='real_name',
            field=models.CharField(max_length=20),
        ),
    ]
