# Generated by Django 3.2.8 on 2021-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_item_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observe',
            name='water',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
