# Generated by Django 3.2.3 on 2021-11-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_alter_student_point_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='point_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
